@startuml
'https://plantuml.com/class-diagram

class MaestroService {
    +searchArtist(name:String , maxArtists: int):Iterable<Artist>
    +getAlbums(artistMbid: String): Iterable<Album>
    +getArtistDetail(artistMbid: String ): ArtistDetail
    +getAlbumTracks(albumMbid: String ) : Iterable<Track>
    +getTracks(artistMbid: String ): Iterable<Track>
}

class LastfmWebApi {
    +searchArtist(String name, int page) : List<ArtistDto>
    +getArtistInfo(String artistMbid): ArtistDetailDto
    +getAlbums(String artistMbid, int page): List<AlbumDto>
    +getAlbumInfo(String albumMbid) : List<TrackDto>
}

interface Request {
    +get(String path): Reader
}

MaestroService "1" o- "1" LastfmWebApi
LastfmWebApi "1" o- "1" Request
@enduml